name = "spin-grannykazino-hu"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-grannykazino.hu"
HMAC_KEY = "09d4bb160a5f698e0c5edc17871e3d412f4f93820cfe6f9828271a0f68f1d635"
COOKIE_NAME = "5i1"
PLAY_PATH = "launch"
BUTTON_ID = "p1145cfcec81914b1d8786b9b1d184af7"
GATE_SALT = "f00cf78b3a0c46c8"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "txqk"
CTA_SELECTOR = ".play-button"
